// Creating a list of currencies.
export const currencyList = [
	{ symbol: 'CAD', name: 'Canadian Dollar' },
	{ symbol: 'HKD', name: 'HongKong Dollar' },
	{ symbol: 'ISK', name: 'Icelandic Króna' },
	{ symbol: 'PHP', name: 'Philippine Peso' },
	{ symbol: 'DKK', name: 'Danish Krone' },
	{ symbol: 'HUF', name: 'Hungarian Forint' },
	{ symbol: 'CZK', name: 'Czech Republic Koruna' },
	{ symbol: 'AUD', name: 'Australian Dollar' },
	{ symbol: 'RON', name: 'Romanian Leu' },
	{ symbol: 'SEK', name: 'Swedish Krona' },
	{ symbol: 'IDR', name: 'Indonesian Rupiah' },
	{ symbol: 'INR', name: 'Indian National Rupee' },
	{ symbol: 'BRL', name: 'Brazilian Real' },
	{ symbol: 'RUB', name: 'Russian Ruble' },
	{ symbol: 'JPY', name: 'Japanese Yen' },
	{ symbol: 'THB', name: 'Thai Baht' },
	{ symbol: 'CHF', name: 'Swiss Franc' },
	{ symbol: 'SGD', name: 'Singapore Dollar' },
	{ symbol: 'PLN', name: 'Polish Zloty' },
	{ symbol: 'BGN', name: 'Bulgarian Lev' },
	{ symbol: 'TRY', name: 'Turkish Lira' },
	{ symbol: 'CNY', name: 'Chinese Yuan' },
	{ symbol: 'NOK', name: 'Norwegian Krone' },
	{ symbol: 'NZD', name: 'New Zealand Dollar' },
	{ symbol: 'ZAR', name: 'South African Rand' },
	{ symbol: 'USD', name: 'United States Dollar' },
	{ symbol: 'MXN', name: 'Mexican Peso' },
	{ symbol: 'ILS', name: 'Israeli New Sheqel' },
	{ symbol: 'GBP', name: 'Great Britain Pound' },
	{ symbol: 'KRW', name: 'South Korean Won' },
	{ symbol: 'MYR', name: 'Malaysian Ringgit' },
];
